### ISSUE TITLE
Less and Sass support

### ISSUE THREAD

**Issue by SebastianStehle** [AngularClass/angular2-conventions-loader#1]
Hi,

I really like the idea and I would like to see support for less and sass.

**Comment by gdi2290** [comment]
ya I can add that right now

**Comment by gdi2290** [comment]
added via https://github.com/AngularClass/angular2-conventions-loader/commit/2f7cacfd1664c0b13cf0a20b269b441e174ae1cc

```es6
{
  test: /\.ts$/,
  loaders: [
    'ts-loader',
    '@angularclass/conventions-loader?cssExtention=.less'
  ]
},
```
