### ISSUE TITLE
Seems not working with async routes

### ISSUE THREAD

**Issue by Mc128k** [AngularClass/angular2-conventions-loader#10]
Hi, I am trying this with Webpack 2 (which supports async routes through loadChildren), and it seems that files in the async components are not "patched" by this module; html and css must be specified manually. Maybe it's a limitation and not a bug, in this case just close this request. Just wanted to inform you guys.

**Comment by gdi2290** [comment]
thanks for the issue, async routes in webpack is handled by another module and is outside of the scope of this one. you can check out our seed repo that has an example of async routes
https://github.com/AngularClass/angular2-seed
