### ISSUE TITLE
Do not load "template: " for @Directive

### ISSUE THREAD

**Issue by Mc128k** [AngularClass/angular2-conventions-loader#11]
Hi all, I just verified that this module wrongly includes the "template: " property in @Directive classes, throwing an error on webpack compilation:

```
 /home/mc128k/node/etiquette-client/node_modules/ng2-select/components/select/off-click.ts:4:13
    Argument of type '{ template: string; selector: string; }' is not assignable to parameter of type 'DirectiveMetadataType'.
  Object literal may only specify known properties, and 'template' does not exist in type 'DirectiveMetadataType'.
[default] Checking finished with 1 errors

```

Here is the code that caused the issue:
```
@Directive({
  selector: '[offClick]'
})
```

As you can read, it's found in the [ng2-select](https://github.com/valor-software/ng2-select) component

**Comment by gdi2290** [comment]
alright I scoped it only to Component
https://github.com/AngularClass/angular2-conventions-loader/commit/5edd34d62d0f30fd3dafbf28860961a6566cb0da
can you try it as 1.0.11
