### ISSUE TITLE
Optional selector convention

### ISSUE THREAD

**Issue by stalniy** [AngularClass/angular2-conventions-loader#12]
In ionic applications you don't need to put selectors on page components otherwise stuff will be broken when you open that page on device.

So, there need to be a callback function, which can detect whether `selector` option is required or not

**Comment by gdi2290** [comment]
how would you detect if it's needed?

**Comment by stalniy** [comment]
@gdi2290 for now I believe it's enough to have an option which allows to skip conventional selector. This is what I did in #13

**Comment by gdi2290** [comment]
k published as 1.0.13
