### ISSUE TITLE
Add @Component ?

### ISSUE THREAD

**Issue by SebastianStehle** [AngularClass/angular2-conventions-loader#3]
I dont kow, if this is a good idea. But there is the convention to suffix the files with .component.ts. This means that we can also add the @component decorator

**Comment by gdi2290** [comment]
can you give an example? this may already be supported

**Comment by SebastianStehle** [comment]
Lets say, I have a file "app.component.ts" and this file contains one class only, then we can add the add the @Component decorator by default.

Or you can check if the class is suffixed with Component

Btw: Which selector is created if the class ends with "Component"?

**Comment by gdi2290** [comment]
if the class ends with Component then it will be `"app-component"` but I can also remove it

**Comment by SebastianStehle** [comment]
If you want to follow the style guide, you should remove it, I think.

> Do append the symbol name with the suffix that it represents.

**Comment by gdi2290** [comment]
I remove `-component` now https://github.com/AngularClass/angular2-conventions-loader/commit/1ce490d2f9b9d98f55e148b7d101515e0d02aecb
make another ussue for `.component`
