### ISSUE TITLE
Feature request: Selector prefix

### ISSUE THREAD

**Issue by SebastianStehle** [AngularClass/angular2-conventions-loader#4]
The convention recommends to use prefixes for selector. Would be awesome to have a setting for this.

E.g. when I use the query "selectorPrefix=my" the selector for the AppComponent class becomes "my-app"

**Comment by gdi2290** [comment]
Ya I can add that

**Comment by gdi2290** [comment]
I added it 
https://github.com/AngularClass/angular2-conventions-loader/commit/e09fefcafe17dbd6efd99a4fdf8a31551d51015d
via 
```es6
{
  test: /\.ts$/,
  loaders: [
    'ts-loader',
    '@angularclass/conventions-loader?selectorPrefix=ng'
  ]
},
```

thanks for a ton of good feedback!
