### ISSUE TITLE
[Windows ]Can't resolve '.home.html'

### ISSUE THREAD

**Issue by j3ddesign** [AngularClass/angular2-conventions-loader#6]
Running angular2-seed I ran into the issue noted at  https://github.com/AngularClass/angular2-seed/issues/6

I had to change the require lines generated to the following
line 147: ` metadata = 'template: require("./' + lastFileName + htmlExtension + '"),\n' + metadata;`
line 163: ` metadata = 'styles: [require("./' + lastFileName + cssExtension + '")],\n' + metadata;`

as before it was simply appending `.` to the start of all file names causing an issue, I'm not sure if this is windows specific as I have no other environments to test on

**Comment by scrapcupcake** [comment]
Sorry, what file did you update this in? I'm searching in the seed repo, can't find it.
